name: MSHV Infra Setup
on: 
  workflow_call:
    inputs:
      RG:
        description: 'Resource Group Name'
        required: true
        type: string
      STORAGE_ACCOUNT:
        description: 'Storage Account Name'
        required: true
        type: string
      DOM0_SKU: 
        description: 'Dom0 VM SKU'
        required: true
        type: string
    secrets:
      MSHV_MI_CLIENT_ID:
        required: true
      MSHV_STORAGE_ACCOUNT_PATH_W2:
        required: true  
      MSHV_STORAGE_ACCOUNT_PATH_W3:
        required: true
      MSHV_STORAGE_ACCOUNT_PATH_WE:
        required: true
      MSHV_USERNAME:
        required: true
      MSHV_PASSWORD:
        required: true
      MSHV_X86_SOURCE_PATH:
        required: true
      MSHV_RUNNER_RG:
        required: true
      MSHV_RUNNER:
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  infrasetup:
    name: MSHV Infra Setup
    runs-on: 
      - self-hosted
      - Linux
    steps:
      - name: Install & login to AZ CLI
        env:
          MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az login --identity --client-id ${MI_CLIENT_ID}

      - name: Create Resource Group & Storage Account
        env:
          LOCATION: westus3
          RG: ${{ inputs.RG }}
        run: |
          az group create --name ${RG} --location ${LOCATION}
          if [ $? -ne 0 ]; then
            echo "Resource group creation failed"
            exit
          fi
          echo "Resource group created"

      - name: Copy/Upload VHD to Azure Storage Account
        env:
          LOCATION: westus3
          MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
          RG: ${{ inputs.RG }}
          SOURCE_PATH_X86: ${{ secrets.MSHV_X86_SOURCE_PATH }}
          STORAGE_ACCOUNT_PATH: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH_W3 }}
          STORAGE_ACCOUNT: ${{ inputs.STORAGE_ACCOUNT }}
        run: |
          set -x

          # Login to Azure
          az login --identity --client-id ${MI_CLIENT_ID}

          # Install AzCopy if not already installed
          if ! command -v azcopy &> /dev/null; then
            echo "AzCopy not found, installing..."
            wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
            tar -xvf azcopy.tar.gz
            sudo mkdir -p /usr/local/bin
            sudo mv azcopy*/azcopy /usr/local/bin/
            sudo chmod +x /usr/local/bin/azcopy
          else
            echo "AzCopy already installed"
          fi

          # AzCopy Login
          azcopy login --identity --identity-client-id ${MI_CLIENT_ID}
          if [ $? -ne 0 ]; then
            echo "AzCopy Login Failed"
            exit 
          fi
          echo "AzCopy Login Succeeded"

          # Copy VHD to Azure Storage Account
          echo "Copying VHD to Azure Storage Account"
          azcopy copy ${SOURCE_PATH_X86} ${STORAGE_ACCOUNT_PATH}/vhds/x86.vhd
          if [ $? -ne 0 ]; then
            echo "AzCopy Failed: VHD upload failed"
            exit 1
          fi
          echo "AzCopy Succeeded: VHD upload complete"

          # Create Blob URL for the VHD
          echo "Creating Blob URL"
          blob_url=$(az storage blob url --auth-mode login --container-name vhds --account-name ${STORAGE_ACCOUNT} --name x86.vhd --output tsv)
          if [ $? -ne 0 ]; then
            echo "Blob URL creation failed"
            exit 1
          fi
          echo "Created Blob URL"

          # Create Image from the VHD
          echo "Creating Image"
          az image create --resource-group ${RG} --name vhd-image --source $blob_url --os-type Linux --location ${LOCATION} --hyper-v-generation V2 || true
          if [ $? -ne 0 ]; then
            echo "Image creation failed"
            exit 1
          fi

      - name: Create DOM0 VM
        env:
          DOM0_SKU: ${{ inputs.DOM0_SKU }}
          LOCATION: westus3
          OS_DISK_SIZE: 512
          RG: ${{ inputs.RG }}
          RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
          RUNNER: ${{ secrets.MSHV_RUNNER }}
          USERNAME: ${{ secrets.MSHV_USERNAME }}
          PASSWORD: ${{ secrets.MSHV_PASSWORD }}
        run: |
          set -x
          # Extract subnet ID from the runner VM
          NIC_ID=$(az vm list --resource-group ${RUNNER_RG} --query "[?location=='${LOCATION}' && name=='${RUNNER}'].networkProfile.networkInterfaces[0].id" -o tsv)
          SUBNET_ID=$(az network nic show --ids $NIC_ID --query "ipConfigurations[0].subnet.id" -o tsv)

          if [[ -z "$SUBNET_ID" ]]; then
            echo "Failed to get Subnet ID."
            exit 1
          fi
          echo "Successfully retrieved subnet ID"

          # Create VM
          echo "Creating VM"
          VM_CREATION=$(az vm create \
            --resource-group ${RG} \
            --name dom0_x86 \
            --subnet $SUBNET_ID \
            --size ${DOM0_SKU} \
            --location ${LOCATION} \
            --image vhd-image \
            --os-disk-size-gb ${OS_DISK_SIZE}\
            --public-ip-sku Standard \
            --storage-sku Premium_LRS \
            --public-ip-address "" \
            --admin-username ${USERNAME} \
            --admin-password ${PASSWORD} \
            --security-type Standard \
            --output json)
          if [ $? -ne 0 ]; then
            echo "VM Creation Failed"
            exit 1
          fi
          echo "VM Creation Succeeded"
          echo $VM_CREATION

          echo "Retrieving VM Private IP address"
          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g ${RG} -n dom0_x86 -d --query privateIps -o tsv)
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve private IP address"
            exit 1
          fi
          echo "Successfully retrieved private IP address"

          # SSH into the VM via sshpass
          echo "Installing sshpass"
          sudo apt install sshpass -y
          echo "Removing the old host key"
          ssh-keygen -R $PRIVATE_IP
          sleep 60
          echo "SSH is now accessible. Connecting..."
          sshpass -p ${PASSWORD} ssh -o StrictHostKeyChecking=no ${USERNAME}@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"

            # Install Dependencies
            sudo tdnf install git moby-engine moby-cli dosfstools mtools build-essential m4 bison flex libuuid-devel qemu-img -y
            curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default -y
            export PATH="\$HOME/.cargo/bin:$PATH"
            cargo --version

            # Clone cloud-hypervisor repo
            git clone https://github.com/cloud-hypervisor/cloud-hypervisor.git

            if [ $? -ne 0 ]; then
              echo "Clone failed for cloud-hypervisor repo"
            fi
            echo "Clone succeeded for cloud-hypervisor repo"

            sudo chown -R ${USERNAME} cloud-hypervisor
            cd cloud-hypervisor
            # git fetch origin --prune
            # git checkout FETCH_HEAD
            sudo mkdir -p /etc/docker/
            echo '{"default-ulimits":{"nofile":{"Hard":65535,"Name":"nofile","Soft":65535}}}' | sudo tee /etc/docker/daemon.json
            sudo systemctl enable docker.service
            sudo systemctl enable containerd.service
            sudo systemctl start docker
            sudo groupadd -f docker
            sudo usermod -a -G docker ${USERNAME}
            sudo systemctl restart docker
          EOF