name: MSHV Performance Metrics Tests (x86-64)
on: 
  workflow_dispatch:
jobs:
  infrasetup:
    name: MSHV Infra Setup
    uses: ./.github/workflows/mshv-infra.yaml
    with:
      # PR_NUMBER: ${{ github.event.pull_request.number }}
      RG: "MSHVPerfMetrics"
      STORAGE_ACCOUNT: "mshvwestus3"
      SKU: "Standard_E8-2ds_v5"
    secrets:
      MSHV_MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
      MSHV_STORAGE_ACCOUNT_PATHS: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATHS }}
      MSHV_USERNAME: ${{ secrets.MSHV_USERNAME }}
      MSHV_PASSWORD: ${{ secrets.MSHV_PASSWORD }}
      MSHV_X86_SOURCE_PATH: ${{ secrets.MSHV_X86_SOURCE_PATH }}
      MSHV_RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
      MSHV_RUNNER: ${{ secrets.MSHV_RUNNER }}
  run_tests:
    name: Performance Metrics Tests (x86-64)
    runs-on:
      - self-hosted
      - Linux
    needs: infrasetup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Az Login
        run: |
          az login --identity --client-id ${{ secrets.MSHV_MI_CLIENT_ID }}

      - name: Run performance metrics tests
        run: |
          set -x
          echo "Retrieving VM Private IP address"
          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g MSHVPerfMetrics-${GITHUB_RUN_ID} -n x86_${GITHUB_RUN_ID} -d --query privateIps -o tsv)
          if [ $? -ne 0 ]; then
           echo "Failed to retrieve private IP address"
           exit 1
          fi
          echo "Successfully retrieved private IP address"
          echo $PRIVATE_IP

          sshpass -p "${{ secrets.MSHV_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.MSHV_USERNAME }}"@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"
            sudo chown -R ${{secrets.MSHV_USERNAME}} cloud-hypervisor
            cd cloud-hypervisor
            sudo ./scripts/dev_cli.sh tests --hypervisor mshv --metrics
          EOF

  cleanup:
    needs: run_tests
    if: always()
    runs-on:
    - self-hosted
    - Linux
    steps:
      - name: Delete Resource Group
        run: |
          az group delete --name MSHVPerfMetrics-${GITHUB_RUN_ID} --yes --no-wait
          echo "Resource group deleted"