name: MSHV Infra Setup
on: 
  workflow_call:
    inputs:
      RG:
        description: 'Resource Group Name'
        required: true
        type: string
      DOM0_SKU: 
        description: 'Dom0 VM SKU'
        required: true
        type: string
    secrets:
      MSHV_MI_CLIENT_ID:
        required: true
      MSHV_STORAGE_ACCOUNT_PATHS:
        required: true
      MSHV_USERNAME:
        required: true
      MSHV_PASSWORD:
        required: true
      MSHV_X86_SOURCE_PATH:
        required: true
      MSHV_RUNNER_RG:
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  infrasetup:
    name: MSHV Infra Setup
    runs-on: 
      - self-hosted
      - Linux
    steps:
      - name: Install & login to AZ CLI
        env:
          MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
        run: |
          if command -v az >/dev/null 2>&1; then
            az --version
          else
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az --version
          fi
          az login --identity --client-id ${MI_CLIENT_ID}

      - name: Copy/Upload VHD to Azure Storage Account & Create RG
        env:
          DOM0_SKU: ${{ inputs.DOM0_SKU }}
          MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
          RG: ${{ inputs.RG }}
          SOURCE_PATH_X86: ${{ secrets.MSHV_X86_SOURCE_PATH }}
          STORAGE_ACCOUNT_PATHS: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATHS }}
          MSHV_RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
        run: |
          set -x

          # Login to Azure
          az login --identity --client-id ${MI_CLIENT_ID}

          if command -v azcopy >/dev/null 2>&1; then
            azcopy --version
          else
            # Install AzCopy
            echo "Installing AzCopy"
            wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
            tar -xvf azcopy.tar.gz
            sudo mkdir -p /usr/local/bin
            sudo mv azcopy*/azcopy /usr/local/bin/
            sudo chmod +x /usr/local/bin/azcopy

            azcopy --version
          fi

          # Determine the location as per quota available
          vcpu=$(echo ${DOM0_SKU} | grep -i -oP '^standard_[A-Za-z]+\K[0-9]+')
          required_vcpu=$((vcpu))
          if [ -z $required_vcpu ]; then
            echo "Can not get required VCPU from SKU name: ${DOM0_SKU}"
            exit 1
          fi
          
          SUPPORTED_LOCATIONS=$(echo ${STORAGE_ACCOUNT_PATHS} | jq 'keys[]' | tr -d \'\")
          for value in ${SUPPORTED_LOCATIONS}; do
            family=$(az vm list-skus --size ${DOM0_SKU} --location $value --resource-type "virtualMachines" --query [0].family |  sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
            if [ -z $family ]; then
              echo "Can not get Family from SKU name: ${DOM0_SKU}"
              exit 1
            fi

            query="[?name.value=='$family'].{Name:name.value,Current:currentValue,Limit:limit}"
            quota_details=$(az vm list-usage --location $value --query $query)

            current_usage=$(echo $quota_details | jq -r '.[0].Current')
            total_quota=$(echo $quota_details | jq -r '.[0].Limit')
            diff=$((total_quota - current_usage))

            if [ $diff -ge $required_vcpu ]; then
              LOCATION=$value
              break
            fi
          done
          if [ -z $LOCATION ]; then
            echo "Location cannot be determined from SUPPORTED_LOCATIONS based on quota"
            exit 1
          fi

          # Create RG for MSHV Infra Setup
          az group create --name ${RG} --location ${LOCATION}
          if [ $? -ne 0 ]; then
            echo "Resource group creation failed"
            exit 1
          fi
          echo "Resource group created"

          MSHV_DEST_STORAGE_PATH=$(echo '{STORAGE_ACCOUNT_PATHS}' | jq -r --arg loc "$LOCATION" '.[$loc]')

          # AzCopy Login
          azcopy login --identity --identity-client-id ${MI_CLIENT_ID}
          if [ $? -ne 0 ]; then
            echo "AzCopy Login Failed"
            exit 1
          fi
          echo "AzCopy Login Succeeded"

          # Copy VHD to Azure Storage Account
          echo "Copying VHD to Azure Storage Account"
          azcopy copy ${SOURCE_PATH_X86} ${MSHV_DEST_STORAGE_PATH}/${GITHUB_RUN_ID}/x86.vhd
          if [ $? -ne 0 ]; then
            echo "AzCopy Failed: VHD upload failed"
            exit 1
          fi
          echo "AzCopy Succeeded: VHD upload complete"

          # Create Blob URL for the VHD
          echo "Creating Blob URL"
          blob_url="${MSHV_DEST_STORAGE_PATH}/${GITHUB_RUN_ID}/x86.vhd"
          echo "Created Blob URL: ${blob_url}"

          # Create Image from the VHD
          echo "Creating Image"
          az image create --resource-group ${RG} --name "vhd-image" --source $blob_url --os-type Linux --location $LOCAATION --hyper-v-generation V2 || true
          if [ $? -ne 0 ]; then
            echo "Image creation failed"
            exit 1
          fi

      - name: Create DOM0 VM
        env:
          DOM0_SKU: ${{ inputs.DOM0_SKU }}
          OS_DISK_SIZE: 512
          RG: ${{ inputs.RG }}
          RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
          RUNNER: ${{ secrets.MSHV_RUNNER }}
          USERNAME: ${{ secrets.MSHV_USERNAME }}
          PASSWORD: ${{ secrets.MSHV_PASSWORD }}
        run: |
          set -x
          # Extract subnet ID
          SUBNET_ID=$(az network vnet list --resource-group ${MSHV_RUNNER_RG} --query "[?contains(location, ${LOCATION})].{Name:name, Location:location,ID:id,SUBNETS:subnets}" | jq -r ".[0].SUBNETS[0].id")

          if [[ -z "$SUBNET_ID" ]]; then
            echo "Failed to get Subnet ID."
            exit 1
          fi
          echo "Successfully retrieved subnet ID"

          # Create VM
          echo "Creating VM"
          VM_CREATION=$(az vm create \
            --resource-group ${RG} \
            --name dom0_x86 \
            --subnet $SUBNET_ID \
            --size ${DOM0_SKU} \
            --location $LOCATION \
            --image vhd-image \
            --os-disk-size-gb ${OS_DISK_SIZE}\
            --public-ip-sku Standard \
            --storage-sku Premium_LRS \
            --public-ip-address "" \
            --admin-username ${USERNAME} \
            --admin-password ${PASSWORD} \
            --security-type Standard \
            --output json)
          if [ $? -ne 0 ]; then
            echo "VM Creation Failed"
            exit 1
          fi
          echo "VM Creation Succeeded"
          echo $VM_CREATION

          echo "Retrieving VM Private IP address"
          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g ${RG} -n dom0_x86 -d --query privateIps -o tsv)
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve private IP address"
            exit 1
          fi
          echo "Successfully retrieved private IP address"

          # SSH into the VM via sshpass
          echo "Installing sshpass"
          sudo apt install sshpass -y
          echo "Removing the old host key"
          ssh-keygen -R $PRIVATE_IP
          sleep 60
          echo "SSH is now accessible. Connecting..."
          sshpass -p ${PASSWORD} ssh -o StrictHostKeyChecking=no ${USERNAME}@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"

            # Install Dependencies
            sudo tdnf install git moby-engine moby-cli dosfstools mtools build-essential m4 bison flex libuuid-devel qemu-img -y
            curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default -y
            export PATH="\$HOME/.cargo/bin:$PATH"
            cargo --version

            # Clone cloud-hypervisor repo
            git clone https://github.com/cloud-hypervisor/cloud-hypervisor.git

            if [ $? -ne 0 ]; then
              echo "Clone failed for cloud-hypervisor repo"
            fi
            echo "Clone succeeded for cloud-hypervisor repo"

            sudo chown -R ${USERNAME} cloud-hypervisor
            cd cloud-hypervisor
            # git fetch origin --prune
            # git checkout FETCH_HEAD
            sudo mkdir -p /etc/docker/
            echo '{"default-ulimits":{"nofile":{"Hard":65535,"Name":"nofile","Soft":65535}}}' | sudo tee /etc/docker/daemon.json
            sudo systemctl enable docker.service
            sudo systemctl enable containerd.service
            sudo systemctl start docker
            sudo groupadd -f docker
            sudo usermod -a -G docker ${USERNAME}
            sudo systemctl restart docker
          EOF
